"""Parity with the qualified pilot (records E12 contract ruling E12-2 and section 13, slice 2).

The contract: "for every built case of every E7 lane, the strict copy's `parse_document`,
`open_set`, cards, and ledger home equal the pilot's, and `render` equals the bytes the pilot's
writers produce for the same facts".

Every E7 fixture lane is built once, into a temporary directory, by the lane's own `build.py`;
nothing under `plugins/recheck-v2/` is written, and the pilot's `recheck_core.ledger` is
imported read-only for the comparison. The wall (contract section 2) is not approached: the
answer key, the held-out trigger set, the routing requests and the routing trials are never
opened, and this suite reads only `evals/fixtures/`, which the contract names as allowed.

Three passes:

1. the strict copy against the pilot's module, on every Markdown document of every built case
   and on every document of this repository;
2. the tolerant reader's frame (lines, sections, slices, blocks) against the strict reader's,
   and every record the strict reader parses against the tolerant reader's item for the same
   line, so that "it accepts everything the strict reader accepts, with the same result"
   (section 11.3) is measured rather than asserted;
3. `render`'s bytes against the pilot's own writers, line by line, for the facts of every
   fixture document and for the synthetic facts of the shapes the fixtures do not hold.
"""
import os
import shutil
import unittest

import testlib

testlib.add_scripts_to_path()
testlib.add_pilot_to_path()

from records_core import ids, legacy, render  # noqa: E402
from recheck_core import ledger as pilot  # noqa: E402  (read-only; the pilot is never written)

STRICT_FUNCTIONS = ("parse_document", "open_set", "card_after", "slice_card", "ledger_home",
                    "append_at_home", "entry_slice", "find_entries", "feature_of")
REPO_LANE = "this repository"
FIXTURE_DOCUMENTS = 238
FIXTURE_STRICT_RECORDS = 179
FIXTURE_TOLERANT_GAIN = 6
"""What the E7 fixture lanes contribute, exactly.

The lanes are generated by their own `build.py` under a fixed configuration, and
`plugins/recheck-v2/` is frozen through E12 (ruling E12-2), so these are constants, not floors: a
lane that stops building, a case that loses its `workspace/`, or a shape that changes is a
failure here rather than a suite that stays green on less. If a lane legitimately changes after
E12, update these three numbers in the same commit and say so."""
"""The label `every_document()` gives this repository's own documents.

Every floor below counts the E7 fixture lanes alone. Those are generated by the lanes' own
`build.py` and are deterministic, so a floor on them is a floor on the suite. Contract section 13
says the counts this repository's documents give go in the builder's report, "not in an assertion
that would pin this repository's documents forever", so they are compared but never counted."""

_LANES = {}
_SCRATCH = []


def setUpModule():
    """Build every E7 lane once, into one temporary directory outside the worktree."""
    base = testlib.make_scratch("records-parity-")
    _SCRATCH.append(base)
    for lane in testlib.eval_lanes():
        out = os.path.join(base, lane)
        os.makedirs(out)
        summary = testlib.build_eval_lane(lane, out)
        _LANES[lane] = [row["path"] for row in summary["cases"]]


def tearDownModule():
    for path in _SCRATCH:
        shutil.rmtree(path, ignore_errors=True)


def lane_documents():
    """(lane, case, workspace-relative doc, text) for every Markdown document of every case."""
    for lane in sorted(_LANES):
        for case_dir in _LANES[lane]:
            workspace = os.path.join(case_dir, "workspace")
            if not os.path.isdir(workspace):
                continue
            for rel in testlib.markdown_documents(workspace):
                with open(os.path.join(workspace, *rel.split("/")), encoding="utf-8") as fh:
                    yield lane, os.path.basename(case_dir), rel, fh.read()


def repo_documents():
    repo = testlib.REPO
    for rel in testlib.markdown_documents(os.path.join(repo, "docs")):
        path = os.path.join(repo, "docs", *rel.split("/"))
        with open(path, encoding="utf-8") as fh:
            yield REPO_LANE, "docs", "docs/" + rel, fh.read()


def every_document():
    for row in lane_documents():
        yield row
    for row in repo_documents():
        yield row


class EveryLaneIsActuallyRead(unittest.TestCase):
    """A lane whose builder changed shape must not drop out of the parity pass in silence."""

    def test_every_lane_built_at_least_one_case(self):
        lanes = testlib.eval_lanes()
        self.assertGreaterEqual(len(lanes), 14, "the E7 fixture lanes: %s" % ", ".join(lanes))
        built = sorted(_LANES)
        for lane in lanes:
            self.assertIn(lane, built, "lane %s built nothing; built: %s" % (lane, ", ".join(built)))
            self.assertGreater(len(_LANES[lane]), 0, "lane %s built no case" % lane)

    def test_every_lane_contributed_at_least_one_compared_document(self):
        seen = {}
        for lane, case, rel, text in lane_documents():
            seen[lane] = seen.get(lane, 0) + 1
        for lane in testlib.eval_lanes():
            self.assertGreater(seen.get(lane, 0), 0,
                               "lane %s contributed no document to the parity pass; a case with "
                               "no workspace/ directory is skipped, so a builder that changed "
                               "shape would leave this suite green on nothing" % lane)

    def test_every_case_of_every_lane_has_a_workspace(self):
        for lane in sorted(_LANES):
            for case_dir in _LANES[lane]:
                self.assertTrue(os.path.isdir(os.path.join(case_dir, "workspace")),
                                "%s / %s has no workspace/" % (lane, os.path.basename(case_dir)))


class TheCopyIsTheSameReader(unittest.TestCase):
    """E12-2: the strict reader in legacy.py reads every E7 fixture exactly as the pilot's does."""

    def test_the_copied_region_is_the_pilot_file_byte_for_byte(self):
        with open(os.path.join(testlib.PILOT_SCRIPTS, "recheck_core", "ledger.py"),
                  encoding="utf-8") as fh:
            original = fh.read()
        with open(os.path.join(testlib.SCRIPTS, "records_core", "legacy.py"),
                  encoding="utf-8") as fh:
            mine = fh.read()
        start = mine.index('"""The record grammar')
        end = mine.index("# =====")
        self.assertEqual(mine[start:end].rstrip("\n") + "\n", original,
                         "the copied region of legacy.py has diverged from the pilot's ledger.py")

    def test_the_header_names_its_origin_and_the_commit(self):
        with open(os.path.join(testlib.SCRIPTS, "records_core", "legacy.py"),
                  encoding="utf-8") as fh:
            head = fh.read(1200)
        self.assertIn("recheck_core/ledger.py", head)
        self.assertIn("fc3945adfbbd793c5782c5be130a07aceadb1982", head)

    def test_every_copied_function_is_present(self):
        for name in STRICT_FUNCTIONS:
            self.assertTrue(hasattr(legacy, name), name)

    def test_parse_document_matches_on_every_built_case_and_on_this_repository(self):
        fixtures = 0
        for lane, case, rel, text in every_document():
            self.assertEqual(legacy.parse_document(text, rel), pilot.parse_document(text, rel),
                             "%s / %s / %s" % (lane, case, rel))
            if lane != REPO_LANE:
                fixtures += 1
        self.assertEqual(fixtures, FIXTURE_DOCUMENTS,
                         "the E7 fixture lanes contributed %d documents, not %d"
                         % (fixtures, FIXTURE_DOCUMENTS))

    def test_open_set_cards_and_home_match_on_every_built_case(self):
        for lane, case, rel, text in every_document():
            where = "%s / %s / %s" % (lane, case, rel)
            mine = legacy.parse_document(text, rel)
            theirs = pilot.parse_document(text, rel)
            self.assertEqual(legacy.open_set(mine), pilot.open_set(theirs), where)
            self.assertEqual(legacy.ledger_home(mine), pilot.ledger_home(theirs), where)
            for name in legacy.slice_names(mine):
                self.assertEqual(legacy.slice_card(mine, name), pilot.slice_card(theirs, name),
                                 "%s slice %s" % (where, name))
                open_entries = [e for e in legacy.open_set(mine)["entries"]
                                if e["slice"] == name and e["state"] == "open"]
                for before in pilot.CARD_VALUES:
                    self.assertEqual(legacy.card_after(before, open_entries),
                                     pilot.card_after(before, open_entries),
                                     "%s slice %s from %s" % (where, name, before))

    def test_appending_at_the_home_produces_the_same_bytes(self):
        text = "- MINOR · src/a.py:1 · (a claim) · fixed · executed the suite\n"
        for lane, case, rel, body in every_document():
            self.assertEqual(legacy.append_at_home(body, text, rel),
                             pilot.append_at_home(body, text, rel),
                             "%s / %s / %s" % (lane, case, rel))


class TheTolerantReaderAcceptsEverythingTheStrictOneDoes(unittest.TestCase):
    """Section 11.3, first sentence, measured on every document the parity pass reads."""

    def frame(self, parsed):
        return (parsed["lines"], parsed["sections"], parsed["slices"], parsed["blocks"])

    def test_the_frame_is_the_strict_readers(self):
        for lane, case, rel, text in every_document():
            strict = legacy.parse_document(text, rel)
            tolerant = legacy.tolerant_document(text, rel)
            self.assertEqual(self.frame(strict), self.frame(tolerant),
                             "%s / %s / %s" % (lane, case, rel))

    def test_a_fenced_grant_claim_is_still_reported_and_never_a_record(self):
        for lane, case, rel, text in every_document():
            strict = legacy.parse_document(text, rel)
            tolerant = legacy.tolerant_document(text, rel)
            lines = set(c["line_no"] for c in tolerant["claims"])
            for claim in strict["claims"]:
                self.assertIn(claim["line_no"], lines, "%s / %s" % (rel, claim["line_no"]))
            for claim in tolerant["claims"]:
                self.assertNotIn(claim["line_no"], set(i["line_no"] for i in tolerant["items"]))

    def bare(self, text):
        return legacy.collapse(text.replace("`", "")) if isinstance(text, str) else text

    def multi(self, item):
        """Does this location field hold one of family L4's separators?"""
        return ids.MULTI_LOCATION_RE.search(item["location"]["raw"].replace("`", "")) is not None

    def test_every_strict_record_has_the_same_reading_in_the_tolerant_one(self):
        compared = fixtures = 0
        self.several = 0
        for lane, case, rel, text in every_document():
            strict = legacy.parse_document(text, rel)
            tolerant = legacy.tolerant_document(text, rel)
            items = dict((item["line_no"], item) for item in tolerant["items"])
            for record in strict["records"]:
                if record["kind"] == "ambiguous":
                    continue
                where = "%s / %s / %s:%d" % (lane, case, rel, record["line_no"])
                item = items.get(record["line_no"])
                self.assertIsNotNone(item, where)
                self.assertEqual(item["kind"], record["kind"], where)
                self.assertEqual(item["severity"], record.get("severity"), where)
                self.assertEqual(item["claim"], record.get("claim"), where)
                if self.multi(item):
                    # Section 11.3 states two rules that cannot both hold on one field: "it
                    # accepts everything the strict reader accepts, with the same result", and
                    # family L4, "several locations separated by `,`, `;`, ` and `, or ` + `, the
                    # first becoming the location and the rest `more`". The pilot's LOCATION_RE
                    # knows no separator, so it swallows the whole field into `file` and takes the
                    # LAST `:N` as the line; the tolerant reader takes the first location and puts
                    # the rest in `more`. The specific rule wins, and nothing depends on the
                    # difference: section 7's key is computed from `location.raw`, which is the
                    # same string either way (asserted below), so both readings join alike.
                    self.several += 1
                    self.assertEqual(ids.location_key(item["location"]),
                                     ids.location_key(record["text"].split(legacy.SEP)[1]), where)
                    if item["location"]["file"] is not None:
                        self.assertTrue(self.bare(record["file"]).startswith(
                            item["location"]["file"]), where)
                    else:
                        # the field's first element is not a `file:N` either, so the tolerant
                        # reader resolved nothing and kept `raw`, which is all section 7 uses
                        self.assertFalse(item["location"]["resolved"], where)
                    compared += 1
                    continue
                # family L1: the tolerant reader removes the backticks the strict reader keeps
                # inside a field it happened to accept anyway, so `file` and `tag` are compared
                # in the form both readers agree on.
                self.assertEqual(item["location"]["file"], self.bare(record.get("file")), where)
                self.assertEqual(item["location"]["line"], record.get("line"), where)
                self.assertEqual(item["location"]["tag"], self.bare(record.get("tag")), where)
                self.assertEqual(item.get("scenario"), record.get("scenario"), where)
                self.assertEqual(item.get("disposition"), record.get("disposition"), where)
                self.assertEqual(item.get("words"), record.get("words"), where)
                self.assertEqual(item.get("date"), record.get("date"), where)
                if record["kind"] == "finding":
                    self.assertEqual(item.get("raised_by"), record.get("found_by"), where)
                if record["kind"] == "defect":
                    self.assertEqual(item.get("slice"), record.get("slice"), where)
                if record["kind"] == "recheck":
                    self.assertEqual(item.get("how"), record.get("how"), where)
                compared += 1
                if lane != REPO_LANE:
                    fixtures += 1
        self.assertEqual(fixtures, FIXTURE_STRICT_RECORDS,
                         "the E7 fixture lanes hold %d strict records, not %d"
                         % (fixtures, FIXTURE_STRICT_RECORDS))
        self.assertGreater(compared, fixtures, "this repository's documents were not compared")
        self.assertGreater(self.several, 0,
                           "no L4 field the strict reader also accepted: the exception above is "
                           "untested, so either the corpus changed or the rule can be dropped")

    def test_the_tolerant_reader_reads_more_than_the_strict_one(self):
        """The point of section 11.3: the ambiguous families become records, never the reverse."""
        gained = 0
        for lane, case, rel, text in every_document():
            strict = legacy.parse_document(text, rel)
            tolerant = legacy.tolerant_document(text, rel)
            stated = sum(1 for i in tolerant["items"] if i["kind"] != "unparsed")
            read = sum(1 for r in strict["records"] if r["kind"] != "ambiguous")
            self.assertGreaterEqual(stated, read, "%s / %s / %s" % (lane, case, rel))
            if lane != REPO_LANE:
                gained += stated - read
        # The E7 lanes are written in the shapes the pilot itself writes, so the tolerant
        # reader gains little there; what each family of section 11.1 gains is `test_legacy.py`'s
        # row, one fixture at a time. The invariant above (never fewer, on every document,
        # this repository's included) is the one that matters here.
        self.assertEqual(gained, FIXTURE_TOLERANT_GAIN,
                         "the E7 fixture lanes gained %d records, not %d"
                         % (gained, FIXTURE_TOLERANT_GAIN))

    def test_the_join_key_is_computed_from_the_location_as_written(self):
        for lane, case, rel, text in every_document():
            for item in legacy.tolerant_document(text, rel)["items"]:
                if item["location"] is None:
                    continue
                self.assertEqual(ids.location_key(item["location"]),
                                 ids.location_key(item["location"]["raw"]),
                                 "%s:%d" % (rel, item["line_no"]))


class RenderMatchesThePilotsWriters(unittest.TestCase):
    """Section 9.4: render equals the bytes the pilot's writers produce for the same facts."""

    def location(self, file, line):
        return {"raw": "%s:%s" % (file, line), "file": file, "line": line, "line_end": None,
                "tag": None, "more": [], "resolved": True}

    def test_a_recheck_line_is_the_pilots(self):
        cases = [
            ("BLOCKER", "src/a.py", 12, "the claim", "fixed", "executed the suite"),
            ("MAJOR", "src/b.py", 4, None, "not fixed", "static: unchanged"),
            ("MINOR", "src/c.py", 99, "a claim · with a separator", "fixed", "executed\nwith a break"),
        ]
        for severity, file, line, claim, disposition, how in cases:
            self.assertEqual(
                render.recheck_text(severity, self.location(file, line), claim, disposition, how),
                pilot.render_recheck_line(severity, file, line, claim, disposition, how),
                "%s %s:%s" % (severity, file, line))

    def test_a_defect_line_is_the_pilots(self):
        for charged in (None, "A", "none"):
            self.assertEqual(
                render.defect_text("MAJOR", self.location("src/d.py", 7), "the claim",
                                   "the scenario", slice_field=charged),
                pilot.render_defect_line("MAJOR", "src/d.py", 7, "the claim", "the scenario",
                                         slice=charged), str(charged))

    def test_a_waiver_line_is_the_pilots(self):
        self.assertEqual(
            render.grant_text(pilot.WAIVED, ["2026-05-06", "BLOCKER", "src/e.py:3"],
                              "the claim", 'the owner said "yes"'),
            pilot.render_waiver("2026-05-06", "BLOCKER", "src/e.py", 3, "the claim",
                                'the owner said "yes"'))

    def test_a_reopening_line_is_the_pilots(self):
        self.assertEqual(
            render.grant_text(pilot.REOPENED, ["2026-05-07", "src/e.py:3"], "the claim", "it came back"),
            pilot.render_reopen("2026-05-07", "src/e.py", 3, "the claim", "it came back"))

    def test_a_block_is_the_pilots(self):
        lines = ["- MINOR · src/a.py:1 · (x) · fixed · executed"]
        for slices in (["A"], ["A", "B"], ["none"]):
            self.assertEqual(legacy.render_block("2026-05-20", slices, lines),
                             pilot.render_block("2026-05-20", slices, lines), str(slices))

    def test_a_rendered_run_is_the_pilots_block_for_the_same_facts(self):
        """The end-to-end shape: events in, the pilot's bytes out."""
        doc = "docs/plans/2026-05-12-history.md"
        location = self.location("src/list.py", 5)
        raised = {"v": 1, "seq": 0, "kind": "finding_raised", "finding": "f1:" + "a" * 20,
                  "slice": "A", "severity": "MAJOR", "location": location, "claim": "the claim",
                  "scenario": "the scenario", "raised_by": "Slice A review", "ledger_doc": doc,
                  "at": "2026-05-12", "actor": {"station": "signoff", "run_id": "r1", "harness": None},
                  "origin": {"kind": "native"}, "source": {"known": False}}
        cleared = {"v": 1, "seq": 1, "kind": "disposition", "finding": raised["finding"],
                   "disposition": "fixed", "how": "executed the list suite", "join_basis": None,
                   "ledger_doc": doc, "at": "2026-05-13T09:00:00Z",
                   "actor": {"station": "recheck", "run_id": "r2", "harness": None},
                   "origin": {"kind": "native"}, "source": {"known": False},
                   "verified_source": {"known": False}}
        out = render.render_run(doc, [raised, cleared], "r2")
        expected = pilot.render_block("2026-05-13", ["A"], [
            pilot.render_recheck_line("MAJOR", "src/list.py", 5, "the claim", "fixed",
                                      "executed the list suite")])
        self.assertEqual(out["block"], expected)
        self.assertEqual(out["text"], expected)
        self.assertEqual(out["slices"], ["A"])

    def test_an_unresolved_location_renders_the_field_as_written(self):
        """The one shape the pilot's writers cannot produce, because it holds no file and line."""
        location = {"raw": "the Tuesday pickup window", "file": None, "line": None,
                    "line_end": None, "tag": None, "more": [], "resolved": False}
        line = render.recheck_text("MINOR", location, "a claim", "fixed", "static")
        self.assertIn("the Tuesday pickup window", line)
        self.assertEqual(line.count(legacy.SEP), 4)

    def test_a_grant_without_words_is_appendix_as_legacy_form(self):
        with_words = render.grant_text(pilot.WAIVED, ["2026-05-06", "BLOCKER", "src/e.py:3"],
                                       "the claim", "yes")
        without = render.grant_text(pilot.WAIVED, ["2026-05-06", "BLOCKER", "src/e.py:3"],
                                    "the claim", None)
        self.assertEqual(with_words.count(legacy.SEP), 5)
        self.assertEqual(without.count(legacy.SEP), 4)
        self.assertTrue(with_words.startswith(without.rstrip("\n")))


class TheCopiedCanonAndIdentityAreTheSame(unittest.TestCase):
    """`canon.py` and `identity.py` are copies of the pilot's, and nothing compared them.

    The outside review's finding 13: mutating `canon.sha256_hex` to return 64 zeros and
    `identity.identity_of` to return a zero commit left all 22 parity tests passing, because
    the suite exercised only the copied READER. These two hold the other two copies to the
    pilot's bytes, over the same documents and the same git fixtures the rest of the suite uses.
    """

    def test_canon_matches_the_pilot_on_every_document_and_on_a_real_file(self):
        from records_core import canon as copied
        from recheck_core import canon as original
        for lane, case, rel, text in every_document():
            self.assertEqual(copied.canonical_json({"text": text}),
                             original.canonical_json({"text": text}), (lane, case, rel))
            self.assertEqual(copied.sha256_hex(text.encode("utf-8")),
                             original.sha256_hex(text.encode("utf-8")), (lane, case, rel))
        path = os.path.join(_SCRATCH[0], "canon-probe")
        copied.atomic_write(path, b"first\n")
        self.assertEqual(copied.sha256_file(path), original.sha256_file(path))
        original.atomic_write(path, b"second\n")
        self.assertEqual(copied.sha256_file(path), original.sha256_file(path))
        self.assertNotEqual(copied.sha256_hex(b""), "0" * 64)

    def test_identity_matches_the_pilot_on_every_git_fixture(self):
        from records_core import identity as copied
        from recheck_core import identity as original
        compared = 0
        for lane in sorted(_LANES):
            for case_dir in _LANES[lane]:
                workspace = os.path.join(case_dir, "workspace")
                if not original.is_work_tree_root(workspace)[0]:
                    continue
                self.assertEqual(copied.identity_of(workspace), original.identity_of(workspace),
                                 (lane, os.path.basename(case_dir)))
                compared += 1
        self.assertGreater(compared, 0, "no E7 lane built a git workspace to compare")


if __name__ == "__main__":
    unittest.main()
