#!/usr/bin/env python3
"""S4: the output block the core generated, checked against OpenCode's real final message.

The block is generated by the core (`recheck_core/result.py`'s `chat_block`), a rendering of
the result record; the adapter's job is to prove the HARNESS delivered it. OpenCode's native
final-message field is the session store's ASSISTANT message text parts, read through this
adapter's own `turns.py` helpers.

Read2's finding (E11-41 R2) is the reason the role filter is load-bearing here: a reader with
no role filter returns the user's own request when the assistant produced no text, and every
delivery check then sees a false positive.

Python 3.9, standard library only. E11-45 S4.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import turns  # noqa: E402

HARNESS = "opencode"


def final_assistant_text(con, session_id):
    """(text, source): OpenCode's own final assistant message, or ("", None).

    Assistant rows only; a user row is never read as the reply.
    """
    found = None
    for row in con.execute(
            "select id, data from message where session_id = ? order by time_created, id",
            (session_id,)):
        try:
            data = json.loads(row["data"])
        except ValueError:
            continue
        if data.get("role") != "assistant":
            continue
        text = turns.message_text(con, row["id"])
        if isinstance(text, str) and text.strip():
            found = text
    if found is None:
        return "", None
    return found, "the session store's last assistant text part"


HEADINGS = ("RECHECK:", "Result:", "Source:", "Method:", "Reason:", "Question:")
COMPLETED_REQUIRED = ("RECHECK:", "Result:", "Source:", "Method:")
STOPPED_REQUIRED = ("RECHECK:", "Reason:")
DISPOSITIONS = ("not_fixed", "fixed", "waived", "reopened")
SEP = "·"


def disposition_of(line):
    """The disposition a line states, as a WHOLE token of the reply grammar (E11-45 R2).

    `fixed` is never matched inside `not fixed`: the line's own separated fields are
    normalised and matched by equality, longest form first.
    """
    if not line:
        return None
    for field in [f for f in line.split(SEP)] + [line]:
        token = field.split("(")[0].strip().lower().replace("-", "_").replace(" ", "_")
        if not token:
            continue
        for word in DISPOSITIONS:
            if token == word:
                return word
        for word in DISPOSITIONS:
            if token.endswith("_" + word) or token.startswith(word + "_"):
                return word
    return None


def _location_of(line):
    """The `file:line` field of a record line, or None."""
    fields = [f.strip() for f in line.split(SEP)]
    for field in fields[1:3]:
        if ":" in field and " " not in field.strip():
            return field.strip()
    return None


def block_parts(block):
    """The generated block split into its heading lines and its per-item record lines."""
    headings, records = [], []
    for raw in (block or "").splitlines():
        line = raw.strip()
        if not line:
            continue
        for head in HEADINGS:
            if line.startswith(head):
                headings.append(line)
                break
        else:
            if SEP in line and _location_of(line):
                records.append(line)
    return headings, records


def check_output_block(block, reply, status="completed"):
    """Does the harness's REAL final assistant text carry the block the core generated?

    E11-45 S4. The block is a rendering of the result record, written by the core; this check
    is the adapter's, against the harness's own native final-message field. Returns
    `{"ok", "why", "missing_headings", "items"}`.

    A session that produced no assistant text fails as "no reply" - never as "no block". The
    two are different findings: one is a delivery failure, the other a content failure, and
    reporting the first as the second sends a reader looking in the wrong place.
    """
    if reply is None or not reply.strip():
        return {"ok": False, "why": "no reply: the session produced no final assistant text",
                "missing_headings": [], "items": []}
    if block is None or not block.strip():
        return {"ok": False, "why": "no block: the core generated no output block",
                "missing_headings": [], "items": []}
    required = COMPLETED_REQUIRED if status == "completed" else STOPPED_REQUIRED
    missing = [head for head in required if head not in reply]
    headings, records = block_parts(block)
    items, disagreed = [], 0
    for line in records:
        location = _location_of(line)
        said = disposition_of(line)
        found, reply_said = None, None
        for candidate in reply.splitlines():
            if location and location in candidate and SEP in candidate:
                found = candidate.strip()
                reply_said = disposition_of(found)
                break
        agrees = None if found is None else (reply_said is not None and reply_said == said)
        if agrees is False:
            disagreed += 1
        items.append({"location": location, "block_disposition": said,
                      "reply_line": found, "reply_disposition": reply_said,
                      "present": found is not None, "agrees": agrees})
    why = None
    if missing:
        why = "no block: the reply is missing %s" % ", ".join(missing)
    elif any(not row["present"] for row in items):
        why = "no block: the reply names no line for %s" % ", ".join(
            row["location"] or "?" for row in items if not row["present"])
    elif disagreed:
        why = "the reply contradicts the result on %d item(s)" % disagreed
    return {"ok": why is None, "why": why or "the reply carries the generated block",
            "missing_headings": missing, "items": items}
