#!/usr/bin/env python3
"""S4: the output block the core generated, checked against Codex's real final message.

The block is generated by the core (`recheck_core/result.py`'s `chat_block`), a rendering of
the result record; the adapter's job is to prove the HARNESS delivered it. Codex's native
final-message field is the last assistant `message` payload of its own `rollout.jsonl`
(`{"type": "response_item", "payload": {"type": "message", "role": "assistant",
"content": [{"type": "output_text", "text": ...}]}}`); `final.md` is a mirror of the same text.

Python 3.9, standard library only. E11-45 S4.
"""
import json
import os

HARNESS = "codex"


def final_assistant_text(harness_dir):
    """(text, source): Codex's own final assistant message, or ("", None).

    Assistant payloads only: a user or tool payload is never read as the reply.
    """
    rollout = os.path.join(harness_dir, "rollout.jsonl")
    found = None
    if os.path.isfile(rollout):
        with open(rollout, "r", encoding="utf-8", errors="replace") as fh:
            for raw in fh:
                raw = raw.strip()
                if not raw:
                    continue
                try:
                    row = json.loads(raw)
                except ValueError:
                    continue
                if not isinstance(row, dict):
                    continue
                payload = row.get("payload")
                if not isinstance(payload, dict) or payload.get("role") != "assistant":
                    continue
                texts = [part.get("text") for part in payload.get("content") or []
                         if isinstance(part, dict) and isinstance(part.get("text"), str)]
                if texts:
                    found = "\n".join(texts)
    if found is not None:
        return found, "rollout.jsonl last assistant message payload"
    mirror = os.path.join(harness_dir, "final.md")
    if os.path.isfile(mirror):
        with open(mirror, "r", encoding="utf-8", errors="replace") as fh:
            return fh.read(), "final.md (the -o mirror of the final message)"
    return "", None


HEADINGS = ("RECHECK:", "Result:", "Source:", "Method:", "Reason:", "Question:")
COMPLETED_REQUIRED = ("RECHECK:", "Result:", "Source:", "Method:")
STOPPED_REQUIRED = ("RECHECK:", "Reason:")
DISPOSITIONS = ("not_fixed", "fixed", "waived", "reopened")
SEP = "·"


def disposition_of(line):
    """The disposition a line states, as a WHOLE token of the reply grammar (E11-45 R2).

    `fixed` is never matched inside `not fixed`: the line's own separated fields are
    normalised and matched by equality, longest form first.
    """
    if not line:
        return None
    for field in [f for f in line.split(SEP)] + [line]:
        token = field.split("(")[0].strip().lower().replace("-", "_").replace(" ", "_")
        if not token:
            continue
        for word in DISPOSITIONS:
            if token == word:
                return word
        for word in DISPOSITIONS:
            if token.endswith("_" + word) or token.startswith(word + "_"):
                return word
    return None


def _location_of(line):
    """The `file:line` field of a record line, or None."""
    fields = [f.strip() for f in line.split(SEP)]
    for field in fields[1:3]:
        if ":" in field and " " not in field.strip():
            return field.strip()
    return None


def block_parts(block):
    """The generated block split into its heading lines and its per-item record lines."""
    headings, records = [], []
    for raw in (block or "").splitlines():
        line = raw.strip()
        if not line:
            continue
        for head in HEADINGS:
            if line.startswith(head):
                headings.append(line)
                break
        else:
            if SEP in line and _location_of(line):
                records.append(line)
    return headings, records


def check_output_block(block, reply, status="completed"):
    """Does the harness's REAL final assistant text carry the block the core generated?

    E11-45 S4. The block is a rendering of the result record, written by the core; this check
    is the adapter's, against the harness's own native final-message field. Returns
    `{"ok", "why", "missing_headings", "items"}`.

    A session that produced no assistant text fails as "no reply" - never as "no block". The
    two are different findings: one is a delivery failure, the other a content failure, and
    reporting the first as the second sends a reader looking in the wrong place.
    """
    if reply is None or not reply.strip():
        return {"ok": False, "why": "no reply: the session produced no final assistant text",
                "missing_headings": [], "items": []}
    if block is None or not block.strip():
        return {"ok": False, "why": "no block: the core generated no output block",
                "missing_headings": [], "items": []}
    required = COMPLETED_REQUIRED if status == "completed" else STOPPED_REQUIRED
    missing = [head for head in required if head not in reply]
    headings, records = block_parts(block)
    items, disagreed = [], 0
    for line in records:
        location = _location_of(line)
        said = disposition_of(line)
        found, reply_said = None, None
        for candidate in reply.splitlines():
            if location and location in candidate and SEP in candidate:
                found = candidate.strip()
                reply_said = disposition_of(found)
                break
        agrees = None if found is None else (reply_said is not None and reply_said == said)
        if agrees is False:
            disagreed += 1
        items.append({"location": location, "block_disposition": said,
                      "reply_line": found, "reply_disposition": reply_said,
                      "present": found is not None, "agrees": agrees})
    why = None
    if missing:
        why = "no block: the reply is missing %s" % ", ".join(missing)
    elif any(not row["present"] for row in items):
        why = "no block: the reply names no line for %s" % ", ".join(
            row["location"] or "?" for row in items if not row["present"])
    elif disagreed:
        why = "the reply contradicts the result on %d item(s)" % disagreed
    return {"ok": why is None, "why": why or "the reply carries the generated block",
            "missing_headings": missing, "items": items}
